DROP TABLE IF EXISTS ADMINS CASCADE;
CREATE TABLE ADMINS(
	ADMIN_ID SERIAL, 
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	PASSWORDS VARCHAR(255) NOT NULL,
	AVATAR BYTEA,
	PHONE_NUM_COUNTRY_CODE INT, 
    PHONE_NUM INT NOT NULL,
	TRUSTED_PHONE INT NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	LANGUAGES TEXT, SIGNATURE TEXT, 
    PRIMARY KEY(ADMIN_ID)
);